# Uncomment the next line to define a global platform for your project
# platform :ios, '15.1'

target 'locavel_cookie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for locavel_cookie
  pod 'NMapsGeometry', '~> 1.0.2'
  pod 'NMapsMap', '~> 3.18.1'

end
