# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Locavel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NMapsMap'
  pod 'naveridlogin-sdk-ios'

  # Pods for Locavel

  target 'LocavelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LocavelUITests' do
    # Pods for testing
  end

end
